import { FloatingAgent } from "@/components/FloatingAgent";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { LocaleProvider } from "@/context/LocaleProvider";
import type { Metadata } from "next";
import { Bebas_Neue, Cairo, Inter, Lexend } from "next/font/google";
import { getMessages, getLocale } from "next-intl/server";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const cairo = Cairo({ subsets: ["latin"], variable: "--font-arabic" });
const lexend = Lexend({ subsets: ["latin"], variable: "--font-heading" });
const bebasNeue = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Next House",
  description: "Generated by Next House",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      className={`${inter.variable} ${cairo.variable} ${lexend.variable} ${bebasNeue.variable}`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <LocaleProvider locale={locale} messages={messages}>
          <Navbar />
          <main className="min-h-dvh">{children}</main>
          <Footer />
          <FloatingAgent />
        </LocaleProvider>
      </body>
    </html>
  );
}
